services:
  - type: web
    name: mapa-denuncias-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        value: https://gfuqruwycmihtpefuilm.supabase.co
      - key: SUPABASE_SERVICE_KEY
        sync: false